---
name: Test

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    container: fedora

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: ./install-dependencies.sh

      - name: Set cargo path
        run: source ~/.cargo/env

      - name: Display system information
        run: cat /etc/os-release && uname -a

      - name: Display compiler version
        run: gcc --version

      - name: Lint
        run: ~/.cargo/bin/cargo fmt --check

      - name: Switch to nightly
        run: rustup default nightly

      - name: Clippy
        run: rustup component add clippy &&
          ~/.cargo/bin/cargo clippy -- -D warnings

      - name: Check docs
        run: RUSTDOCFLAGS="-D warnings" ~/.cargo/bin/cargo doc --no-deps

      - name: Install riscv toolchain
        run: rustup target add riscv64gc-unknown-linux-gnu

      - name: Build on riscv
        run: ~/.cargo/bin/cargo build --target riscv64gc-unknown-linux-gnu

      - name: Unit tests
        run: ~/.cargo/bin/cargo test

      - name: Integration tests
        run: ./test.sh
