---
name: Test

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: cargo fmt --check

      - name: Switch to nightly
        run: rustup default nightly

      - name: Clippy
        run: rustup component add clippy &&
          cargo clippy -- -D warnings

      - name: Check docs
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

      - name: Unit tests
        run: cargo test

      - name: Integration tests
        run: ./test.sh
